version: "3.7"

x-restart-policy: &restart_policy
  restart: unless-stopped

services:
  thread_bot:
    << : *restart_policy
    build:
      context: .
      dockerfile: Dockerfile
    container_name: thread_bot
    init: true

    env_file:
      - .env

    volumes:
      - .:/thread_bot
